server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.hipudding.cn:3306/deliveroo?characterEncoding=utf8&useSSL=false
    username: root
    password: test@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database : MYSQL
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  thymeleaf:
      cache: false
      mode: LEGACYHTML5
      content-type: text/html

  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  resources:
    static-locations: classpath:/static/,classpath:/templates/,file:${img_path}

logging:
  level: info
  file: ${log_path}/deliveroo.log
  root: INFO


img_path: ./image
log_path: ./logs
